# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759d5b9dafa5a5af18aec6711cdd56cd983d8125e1eb0fbef91500b52d0d4d2507c35ee0d20a57edb61e788b01855d6d9f4881bf8f43348c887a21ad36960529

test:
  secret_key_base: b043bf13fbd4bcd5861706c3e33f059bc18236d0d3c2073b45c8cf64dcb52adb7639b06c2477cc1ed2c1552edc1f4e2965d1043a17dedd59d4b39c8078534c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
