require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NomineesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Nominee. As you add validations to Nominee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NomineesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all nominees as @nominees" do
      nominee = Nominee.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:nominees)).to eq([nominee])
    end
  end

  describe "GET #show" do
    it "assigns the requested nominee as @nominee" do
      nominee = Nominee.create! valid_attributes
      get :show, {:id => nominee.to_param}, valid_session
      expect(assigns(:nominee)).to eq(nominee)
    end
  end

  describe "GET #new" do
    it "assigns a new nominee as @nominee" do
      get :new, {}, valid_session
      expect(assigns(:nominee)).to be_a_new(Nominee)
    end
  end

  describe "GET #edit" do
    it "assigns the requested nominee as @nominee" do
      nominee = Nominee.create! valid_attributes
      get :edit, {:id => nominee.to_param}, valid_session
      expect(assigns(:nominee)).to eq(nominee)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Nominee" do
        expect {
          post :create, {:nominee => valid_attributes}, valid_session
        }.to change(Nominee, :count).by(1)
      end

      it "assigns a newly created nominee as @nominee" do
        post :create, {:nominee => valid_attributes}, valid_session
        expect(assigns(:nominee)).to be_a(Nominee)
        expect(assigns(:nominee)).to be_persisted
      end

      it "redirects to the created nominee" do
        post :create, {:nominee => valid_attributes}, valid_session
        expect(response).to redirect_to(Nominee.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved nominee as @nominee" do
        post :create, {:nominee => invalid_attributes}, valid_session
        expect(assigns(:nominee)).to be_a_new(Nominee)
      end

      it "re-renders the 'new' template" do
        post :create, {:nominee => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested nominee" do
        nominee = Nominee.create! valid_attributes
        put :update, {:id => nominee.to_param, :nominee => new_attributes}, valid_session
        nominee.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested nominee as @nominee" do
        nominee = Nominee.create! valid_attributes
        put :update, {:id => nominee.to_param, :nominee => valid_attributes}, valid_session
        expect(assigns(:nominee)).to eq(nominee)
      end

      it "redirects to the nominee" do
        nominee = Nominee.create! valid_attributes
        put :update, {:id => nominee.to_param, :nominee => valid_attributes}, valid_session
        expect(response).to redirect_to(nominee)
      end
    end

    context "with invalid params" do
      it "assigns the nominee as @nominee" do
        nominee = Nominee.create! valid_attributes
        put :update, {:id => nominee.to_param, :nominee => invalid_attributes}, valid_session
        expect(assigns(:nominee)).to eq(nominee)
      end

      it "re-renders the 'edit' template" do
        nominee = Nominee.create! valid_attributes
        put :update, {:id => nominee.to_param, :nominee => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested nominee" do
      nominee = Nominee.create! valid_attributes
      expect {
        delete :destroy, {:id => nominee.to_param}, valid_session
      }.to change(Nominee, :count).by(-1)
    end

    it "redirects to the nominees list" do
      nominee = Nominee.create! valid_attributes
      delete :destroy, {:id => nominee.to_param}, valid_session
      expect(response).to redirect_to(nominees_url)
    end
  end

end
